name: MY FIRST WORKLOAD

on:
  push:
    branches: 
       - 'v[0-9]+.[0-9]+'
      

jobs:
  my-first-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: List file
      run: |
         pwd
         ls -al
    - name: using Checkout
      uses: actions/checkout@v3
    - name: List file
      run: |
        pwd
        ls -al
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
    - name: Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.MY_NOTHING }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nSoe La Pyae Htun"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\nA0123456B"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\ne123456@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\nhttps://github.com/soelapyae-htun/fortune"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\nhttps://eminent-planes-production.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://eminent-planes-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
   

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.MY_SOMETHING }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

