name: My First Workflow

#trigger 
on:
  push:
    branches:
      - "v[0-9]+.[0-9]+"

#Jobs in the workflow
jobs:
  my-first-workflow:
    #OS that this job will be running on
    runs-on: ubuntu-latest

    #List of steps to perform task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: echo information about the contex
      run: echo "head_ref - ${{ github.head_ref }}, owner - ${{github.repository_owner}}"
    - name: List runner name
      run: echo "runner os - ${{ runner.os }}"
    - name: MY_NODE
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.MY_NOTHING }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nSoe La Pyae Htun"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\nA*******"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\e1045754@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\nhttps://github.com/soelapyae-htun/fortune.git
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\nhttps://eminent-planes-production.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://eminent-planes-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.MY_SOMETHING }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK



